/*
Problem: Find the Difference

Difficulty: Easy

Source: LeetCode 389

Description:
You are given two strings s and t.

String t is generated by randomly shuffling string s
and then adding one more letter at a random position.

Return the letter that was added to t.

Example 1:
Input:
s = "abcd"
t = "abcde"

Output:
e

Example 2:
Input:
s = ""
t = "y"

Output:
y

Pattern: Hashing / Frequency Counting

Time Complexity: O(n)
Space Complexity: O(1)

Approach:
1. Create a frequency array of size 26.
2. Count all characters present in string s.
3. Traverse string t and decrease frequency.
4. If frequency becomes negative,
   that character is the extra character.
5. Return the extra character.
*/

import java.util.Scanner;

public class FindTheDifference {

    public static char findTheDifference(String s, String t) {

        int[] count = new int[26];

        for (int i = 0; i < s.length(); i++) {
            count[s.charAt(i) - 'a']++;
        }

        for (int i = 0; i < t.length(); i++) {
            count[t.charAt(i) - 'a']--;

            if (count[t.charAt(i) - 'a'] < 0) {
                return t.charAt(i);
            }
        }

        return ' ';
    }

    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);

        System.out.print("Enter string s: ");
        String s = sc.nextLine();

        System.out.print("Enter string t: ");
        String t = sc.nextLine();

        char result = findTheDifference(s, t);

        System.out.println("Added Character: " + result);

        sc.close();
    }
}